"""upgrading

Revision ID: 3943b52527f3
Revises: 01ca703bab97
Create Date: 2023-02-06 00:18:17.109924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3943b52527f3'
down_revision = '01ca703bab97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
