"""empty message

Revision ID: 4ef13231870f
Revises: 9ebdd0c528a6
Create Date: 2023-02-03 22:58:45.515602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef13231870f'
down_revision = '9ebdd0c528a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('staff_id')
        batch_op.drop_column('retailer_id')

    # ### end Alembic commands ###
