"""main

Revision ID: 6297d5ca5470
Revises: 3943b52527f3
Create Date: 2023-02-07 00:27:27.165543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6297d5ca5470'
down_revision = '3943b52527f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item__img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('staff_id')
        batch_op.drop_column('retailer_id')

    op.drop_table('photo')
    op.drop_table('item__img')
    # ### end Alembic commands ###
