"""empty message

Revision ID: 831f9824c423
Revises: b76f41534ea0
Create Date: 2023-01-05 11:05:11.204335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831f9824c423'
down_revision = 'b76f41534ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retail_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=60), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('budget', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=False),
    sa.Column('messages', sa.INTEGER(), nullable=False),
    sa.Column('shoppingCartCount', sa.INTEGER(), nullable=False),
    sa.Column('profits', sa.INTEGER(), nullable=False),
    sa.Column('spending', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
